name: agriconnect
description: "AgriConnect is a transformative mobile application designed to bridge the gap between farmers, suppliers, and agricultural experts. By leveraging modern technology, AgriConnect empowers farmers with real-time access to resources, advice, and marketplaces. Whether you're seeking high-quality seeds, expert farming tips, or a platform to sell your produce, AgriConnect connects you to a thriving agricultural community, ensuring sustainability, growth, and innovation in farming practices."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  provider: ^6.1.5
  path: ^1.9.1
  flutter_phone_direct_caller: ^2.1.1
  flutter_local_notifications: ^19.2.1
  supabase_flutter: ^2.9.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

flutter_native_splash:
  color: "#9fe69a"
  image: assets/images/logo-transparent.png
  color_dark: "#1a1a1a"
  image_dark: assets/images/logo-transparent.png

  android_12:
    image: assets/images/logo-transparent.png
    icon_background_color: "#9fe69a"
    image_dark: assets/images/logo-transparent.png
    icon_background_color_dark: "#1a1a1a"

  web: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff "

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
